name: Dev testing

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Some text to print'
        required: false 
        type: string

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Print the value of version
        run: echo ${{ github.event.inputs.version }}
          
      - if: ${{ github.event.inputs.version == '' }}
        name: Check if version does not exist
        run: echo version does not exist
        
      - if: ${{ github.event.inputs.version != '' }}
        name: Check if version exists
        run: echo version exists
