name: Compile Pack (test)

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the pack'
        required: true 
        type: string

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Compile pack
        uses: ComunidadAylas/PackSquash-action@v3.0.0
        with:
          path: 'test'
#           artifact_name: s6pack
#           zip_spec_conformance_level: disregard
#           size_increasing_zip_obfuscation: true

        
      # Rename artifact
      # With given version
      - if: ${{ github.event.inputs.version != '' }}
        name: Rename artifact (with given version)
        run: mv /home/runner/work/_temp/packsquash/pack.zip s6pack-${{ github.event.inputs.version }}.zip

      # With PR version
      - if: ${{ github.event.inputs.version == '' }}
        name: Rename artifact (with PR name as version)
        run: mv /home/runner/work/_temp/packsquash/pack.zip s6pack-${{ github.event.pull_request.title }}.zip


      # Add version to version.txt
      # With given version
      - if: ${{ github.event.inputs.version != '' }}
        name: Add version to version file (with given version)
        run: echo "${{ github.event.inputs.version }}" > version.txt
        
      # With PR version
      - if: ${{ github.event.inputs.version == '' }}
        name: Add version to version file (with PR name as version)
        run: echo "${{ github.event.pull_request.title }}" > version.txt

      
      # Upload artifact
      # With given version
      - if: ${{ github.event.inputs.version != '' }}
        name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: s6pack-${{ github.event.inputs.version }}.zip
          path: s6pack-${{ github.event.inputs.version }}.zip
          if-no-files-found: error
      
      # With PR version
      - if: ${{ github.event.inputs.version == '' }}
        name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: s6pack-${{ github.event.inputs.version }}.zip
          path: s6pack-${{ github.event.inputs.version }}.zip
          if-no-files-found: error
      

      # Upload version
      - name: Upload version
        uses: actions/upload-artifact@v3.1.0
        with:
          name: version.txt
          path: version.txt
          if-no-files-found: error

      # Release artifacts
      # With given version
      - if: ${{ github.event.inputs.version != '' }}
        name: Release artifact (with given version)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "s6pack-${{ github.event.inputs.version }}.zip, version.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}

      # With PR version
      - if: ${{ github.event.inputs.version == '' }}
        name: Release artifact (with PR name as version)
        uses: ncipollo/release-action@v1
        with:
          artifacts: "s6pack-${{ github.event.pull_request.title }}.zip, version.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.pull_request.title }}
          
      
