name: Compile Pack (test)

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the pack'
        required: true 
        type: string

jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Compile pack
        uses: ComunidadAylas/PackSquash-action@v3.0.0
        with:
          path: 'test'
      
      - name: Rename artifact
        run: mv /home/runner/work/_temp/packsquash/pack.zip /home/runner/work/_temp/packsquash/testpack.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: s6pack.zip
          path: /home/runner/work/_temp/packsquash/testpack.zip
          if-no-files-found: error
          
      - name: Print hash
        run: echo ${{ hashFiles('/home/runner/work/_temp/packsquash/testpack.zip') }}
          
#       - if: ${{ github.event.inputs.version != '' }}
#         name: Release artifact (with given version)
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: /home/runner/work/_temp/packsquash/s6pack.zip
#           token: ${{ secrets.GITHUB_TOKEN }}
#           tag: ${{ github.event.inputs.version }}


#       - if: ${{ github.event.inputs.version == '' }}
#         name: Release artifact (with PR name as version)
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: /home/runner/work/_temp/packsquash/s6pack.zip
#           token: ${{ secrets.GITHUB_TOKEN }}
#           tag: ${{ github.event.pull_request.title }}
          
      
